# Generated by Django 5.2.7 on 2025-10-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_management', '0002_exercisecategory_mealcategory_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, help_text='Link to a reference image or GIF that demonstrates the movement.'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to a demo video (YouTube, Loom, MP4, etc.).'),
        ),
    ]
