# Generated by Django 5.2.7 on 2025-10-23 19:40

from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models


MUSCLE_CHOICES = [
    ("Abdominals", "Abdominals"),
    ("Obliques", "Obliques"),
    ("Lower Back", "Lower Back"),
    ("Upper Back", "Upper Back"),
    ("Chest", "Chest"),
    ("Shoulders", "Shoulders"),
    ("Biceps", "Biceps"),
    ("Triceps", "Triceps"),
    ("Forearms", "Forearms"),
    ("Quadriceps", "Quadriceps"),
    ("Hamstrings", "Hamstrings"),
    ("Glutes", "Glutes"),
    ("Calves", "Calves"),
    ("Hip Flexors", "Hip Flexors"),
    ("Adductors", "Adductors"),
    ("Rotator Cuff", "Rotator Cuff"),
    ("Cardiovascular System", "Cardiovascular System"),
    ("Neck", "Neck"),
    ("Grip", "Grip"),
]


def _split(value: str) -> list[str]:
    if not value:
        return []
    return [part.strip() for part in value.split(",") if part.strip()]


def forwards(apps, schema_editor):
    Exercise = apps.get_model("personal_management", "Exercise")
    for exercise in Exercise.objects.all():
        exercise.primary_muscles_tmp = _split(exercise.primary_muscles)
        exercise.secondary_muscles_tmp = _split(exercise.secondary_muscles)
        exercise.save(update_fields=["primary_muscles_tmp", "secondary_muscles_tmp"])


def backwards(apps, schema_editor):
    Exercise = apps.get_model("personal_management", "Exercise")
    for exercise in Exercise.objects.all():
        exercise.primary_muscles = ", ".join(exercise.primary_muscles_tmp)
        exercise.secondary_muscles = ", ".join(exercise.secondary_muscles_tmp)
        exercise.save(update_fields=["primary_muscles", "secondary_muscles"])


class Migration(migrations.Migration):

    dependencies = [
        ("personal_management", "0003_exercise_image_url_exercise_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="primary_muscles_tmp",
            field=ArrayField(
                base_field=models.CharField(choices=MUSCLE_CHOICES, max_length=32),
                default=list,
                size=6,
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="secondary_muscles_tmp",
            field=ArrayField(
                base_field=models.CharField(choices=MUSCLE_CHOICES, max_length=32),
                default=list,
                blank=True,
                size=6,
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="exercise",
            name="primary_muscles",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="secondary_muscles",
        ),
        migrations.RenameField(
            model_name="exercise",
            old_name="primary_muscles_tmp",
            new_name="primary_muscles",
        ),
        migrations.RenameField(
            model_name="exercise",
            old_name="secondary_muscles_tmp",
            new_name="secondary_muscles",
        ),
    ]
