# Generated by Django 5.2.7 on 2025-10-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_management", "0004_exercise_muscle_arrays"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="image_url",
            field=models.URLField(blank=True, help_text="Link to a reference image for the meal."),
        ),
        migrations.AddField(
            model_name="meal",
            name="recipe_url",
            field=models.URLField(blank=True, help_text="Link to a full recipe or video walkthrough."),
        ),
    ]
