# Generated by Django 5.2.7 on 2025-10-23 20:05

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("personal_management", "0005_meal_media_urls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PomodoroProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_focus_minutes", models.PositiveIntegerField(default=0)),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                ("xp", models.PositiveIntegerField(default=0)),
                ("level", models.PositiveIntegerField(default=1)),
                ("coins", models.PositiveIntegerField(default=0)),
                ("streak_count", models.PositiveIntegerField(default=0)),
                ("best_streak", models.PositiveIntegerField(default=0)),
                ("last_completed_date", models.DateField(blank=True, null=True)),
                ("user", models.OneToOneField(on_delete=models.deletion.CASCADE, related_name="pomodoro_profile", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="PomodoroSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("focus_minutes", models.PositiveIntegerField()),
                ("short_break_minutes", models.PositiveIntegerField(default=5)),
                ("long_break_minutes", models.PositiveIntegerField(default=15)),
                ("cycles_before_long_break", models.PositiveIntegerField(default=4)),
                ("current_cycle", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("completed", "Completed"), ("cancelled", "Cancelled")],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_focus_minutes", models.PositiveIntegerField(default=0)),
                ("tree_type", models.CharField(blank=True, max_length=32)),
                ("profile", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="sessions", to="personal_management.pomodoroprofile")),
            ],
            options={"ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="PomodoroTree",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tree_type", models.CharField(max_length=32)),
                ("focus_minutes", models.PositiveIntegerField()),
                ("planted_at", models.DateTimeField(auto_now_add=True)),
                ("profile", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="forest", to="personal_management.pomodoroprofile")),
            ],
            options={"ordering": ["-planted_at"]},
        ),
    ]
